version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
    depends_on:
      - db

  db:
    image: mongo:6.0.2
    profiles:
      - dev
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
      #- ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      #- MONGO_INITDB_DATABASE=app
      # entrypoint.init.db
  
  db_test:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    tmpfs:
      - /data/db
  
  mongo-express:
    image: mongo-express
    profiles:
      - dev
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - db

#npm run test ----> mongo